// Backend Audio Player - Plays audio generated by server TTS

function playAudioFromBackend(audioBase64) {
    // Stop any currently playing audio
    if (window.currentAudio) {
        window.currentAudio.pause();
        window.currentAudio = null;
    }

    try {
        // Convert base64 to audio blob
        const audioData = atob(audioBase64);
        const arrayBuffer = new ArrayBuffer(audioData.length);
        const uint8Array = new Uint8Array(arrayBuffer);

        for (let i = 0; i < audioData.length; i++) {
            uint8Array[i] = audioData.charCodeAt(i);
        }

        const blob = new Blob([uint8Array], { type: 'audio/mp3' });
        const audioUrl = URL.createObjectURL(blob);

        // Create and play audio
        window.currentAudio = new Audio(audioUrl);

        window.currentAudio.onended = () => {
            URL.revokeObjectURL(audioUrl);
            window.currentAudio = null;
            window.isAISpeaking = false; // Mark AI as done speaking
            window.isProcessing = false; // Reset processing flag

            console.log('✅ AI finished speaking, waiting before listening...');

            // Auto-restart listening if in conversation mode
            if (window.conversationMode && window.recognition) {
                // Longer delay to prevent picking up AI's own voice or immediate restart
                setTimeout(() => {
                    if (!window.isProcessing && window.conversationMode) {
                        try {
                            window.recognition.start();
                            console.log('🎤 Auto-restarted listening');
                        } catch (error) {
                            console.log('Recognition auto-restart skipped:', error.message);
                        }
                    }
                }, 1500); // Wait 1.5 seconds before listening again (increased from 500ms)
            }
        };

        window.currentAudio.onerror = (error) => {
            console.error('Audio playback error:', error);
            URL.revokeObjectURL(audioUrl);
            window.currentAudio = null;
            window.isAISpeaking = false;
            window.isProcessing = false; // Reset on error
        };

        window.currentAudio.play().catch(err => {
            console.error('Failed to play audio:', err);
            window.isAISpeaking = false;
            window.isProcessing = false; // Reset on play error
        });

        console.log('✅ Playing audio from backend TTS');

    } catch (error) {
        console.error('Error decoding audio:', error);
        window.isAISpeaking = false;
        window.isProcessing = false; // Reset on decode error
    }
}

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { playAudioFromBackend };
}
