// Backend Audio Player - Plays audio generated by server TTS
let currentAudio = null;

function playAudioFromBackend(audioBase64) {
    // Stop any currently playing audio
    if (currentAudio) {
        currentAudio.pause();
        currentAudio = null;
    }

    try {
        // Convert base64 to audio blob
        const audioData = atob(audioBase64);
        const arrayBuffer = new ArrayBuffer(audioData.length);
        const uint8Array = new Uint8Array(arrayBuffer);

        for (let i = 0; i < audioData.length; i++) {
            uint8Array[i] = audioData.charCodeAt(i);
        }

        const blob = new Blob([uint8Array], { type: 'audio/mp3' });
        const audioUrl = URL.createObjectURL(blob);

        // Create and play audio
        currentAudio = new Audio(audioUrl);

        currentAudio.onended = () => {
            URL.revokeObjectURL(audioUrl);
            currentAudio = null;
        };

        currentAudio.onerror = (error) => {
            console.error('Audio playback error:', error);
            URL.revokeObjectURL(audioUrl);
            currentAudio = null;
        };

        currentAudio.play().catch(err => {
            console.error('Failed to play audio:', err);
        });

        console.log('✅ Playing audio from backend TTS');

    } catch (error) {
        console.error('Error decoding audio:', error);
    }
}

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { playAudioFromBackend };
}
